- name: Playbook for installing one package
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: create files
      file:
        path: /tmp/authorized_key.{{item}}.pub
        state: touch
    with_items:
      - ulan
      - miki