- name: Playbook for installing one package
  hosts: all 
  become: yes
  become_method: sudo
  tasks:
    - name: install package
      package:
        name: "{{package_name}}"
        state: present
