---
- name: create user and place ssh key
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: create user
    user: name="{{ item.username}}"
    with_items: "{{ username}}"


  - name: placing ssh
    authorized_key: user="{{item.username}}" key="{{ lookup('file', './keyfiles/authorized_key.{{item.username}}.pub')}} " 
    with_items: "{{ username }}"


