---
- name: Playbook for tasks
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tasks: 
    - name: add multiple users
      user: 
        name: "{{item}}"
        state: present  
      with_items:
        - ulan
        - miki


  - name: placing ssh
    authorized_key: user="{{item.username}}" key="{{ lookup('file', './keyfiles/authorized_key.{{item.username}}.pub')}} " 
    with_items: "{{ username }}"


